[project]
name = "vocora-server"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ihar Myshkevich", email = "33940074+IgorMy@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic==1.20.0",
    "fastapi[standard]==0.142.2",
    "pgvector==0.5.0",
    "procrastinate==3.10.0",
    "psycopg[binary,pool]==3.3.6",
    "pydantic-settings==2.15.0",
    "scalar-fastapi==1.9.1",
    "slowapi==0.1.10",
    "sqlmodel==0.0.47",
]

[tool.fastapi]
entrypoint = "src.main:app"

[tool.uv]
package = false

[tool.ruff.lint]
extend-select = ["I", "TID252"]  # I: orden de imports, TID252: prohibir relativos

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"
