"""add recording table

Revision ID: 3dd6ec913e7c
Revises: eaff1e2332da
Create Date: 2026-10-05 22:03:50.778710

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dd6ec913e7c"
down_revision: str | Sequence[str] | None = "eaff1e2332da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recording",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("folder", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contact", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("audio_format", sa.String(), nullable=False),
        sa.Column("mixed_sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uplink_sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "downlink_sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "process_log", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transcription", sa.Text(), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audit_request_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_request_id"], ["audit_request.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("folder"),
    )
    op.create_index(
        op.f("ix_recording_contact"), "recording", ["contact"], unique=False
    )
    op.create_index(op.f("ix_recording_date"), "recording", ["date"], unique=False)
    op.create_index(op.f("ix_recording_status"), "recording", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recording_status"), table_name="recording")
    op.drop_index(op.f("ix_recording_date"), table_name="recording")
    op.drop_index(op.f("ix_recording_contact"), table_name="recording")
    op.drop_table("recording")
    # ### end Alembic commands ###
