"""add deleted_at to recording

Revision ID: 9d953a8e9616
Revises: a304dbe52e6d
Create Date: 2026-10-06 19:28:57.664938

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d953a8e9616"
down_revision: str | Sequence[str] | None = "a304dbe52e6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recording", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_recording_deleted_at"), "recording", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recording_deleted_at"), table_name="recording")
    op.drop_column("recording", "deleted_at")
    # ### end Alembic commands ###
