"""add segments to recording

Revision ID: a304dbe52e6d
Revises: 40bb0f1308ab
Create Date: 2026-10-06 18:17:41.777440

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a304dbe52e6d"
down_revision: str | Sequence[str] | None = "40bb0f1308ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recording",
        sa.Column("segments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recording", "segments")
    # ### end Alembic commands ###
