"""add audit_request table

Revision ID: eaff1e2332da
Revises: 56f784067d71
Create Date: 2026-10-05 12:40:01.290656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eaff1e2332da'
down_revision: Union[str, Sequence[str], None] = '56f784067d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_request_client_ip'), 'audit_request', ['client_ip'], unique=False)
    op.create_index(op.f('ix_audit_request_created_at'), 'audit_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_request_path'), 'audit_request', ['path'], unique=False)
    op.create_index(op.f('ix_audit_request_status_code'), 'audit_request', ['status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_request_status_code'), table_name='audit_request')
    op.drop_index(op.f('ix_audit_request_path'), table_name='audit_request')
    op.drop_index(op.f('ix_audit_request_created_at'), table_name='audit_request')
    op.drop_index(op.f('ix_audit_request_client_ip'), table_name='audit_request')
    op.drop_table('audit_request')
    # ### end Alembic commands ###
