"""add audit_change table

Revision ID: f30f9975791d
Revises: 3dd6ec913e7c
Create Date: 2026-10-06 15:45:53.050057

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f30f9975791d"
down_revision: str | Sequence[str] | None = "3dd6ec913e7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_change",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("table_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_change_created_at"), "audit_change", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_change_record_id"), "audit_change", ["record_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_change_table_name"), "audit_change", ["table_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_change_table_name"), table_name="audit_change")
    op.drop_index(op.f("ix_audit_change_record_id"), table_name="audit_change")
    op.drop_index(op.f("ix_audit_change_created_at"), table_name="audit_change")
    op.drop_table("audit_change")
    # ### end Alembic commands ###
